# Generated by Django 4.0.4 on 2022-11-02 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_student_year_of_passing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
    ]
