# Generated by Django 4.1.3 on 2022-11-05 11:46

import base.helpers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_post_offer_id_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='offer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='base.placement_detail'),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_passing',
            field=models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026)], default=base.helpers.current_year, verbose_name='year_of_passing'),
        ),
    ]
