# Generated by Django 4.1.3 on 2022-11-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement_detail',
            name='intern',
            field=models.BooleanField(default=False),
        ),
    ]
