# Generated by Django 4.1.3 on 2022-11-07 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_placement_detail_table_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='placement_detail',
            table='placement_Detail',
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
