# Generated by Django 4.1.3 on 2022-11-07 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_placement_detail_table_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='placement_detail',
            table='Placement_Detail',
        ),
    ]
